"""
Ontology Population Pipeline for SENSO Framework — Paper 1

Populates the Software Evolution Ontology (SEO) from GitHub repository data.
For a given repository, this pipeline:
  1. Mines git history via PyDriller (commits, authors, files, churn)
  2. Computes cyclomatic complexity via lizard on monthly snapshots
  3. Parses package manifests (requirements.txt, package.json, pom.xml)
  4. Maps extracted data to SEO ontology classes via JSON-LD intermediate format
  5. Computes derived properties (phase labels, law conformance, agent adoption)
  6. Loads triples into Apache Jena Fuseki via SPARQL INSERT
  7. Runs HermiT consistency check via Owlready2

Used by: Paper 1 (ontology population, RQ2 accuracy evaluation)

Usage:
    python populate.py --repo owner/name --fuseki-url http://localhost:3030 --dataset seo
    python populate.py --repos-file repos.json --fuseki-url http://localhost:3030 --dataset seo
"""

import argparse
import json
import logging
import os
import re
import subprocess
import sys
import tempfile
import uuid
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Optional
from xml.etree import ElementTree

import yaml
from dotenv import load_dotenv

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger("senso.population")

# ── Constants ────────────────────────────────────────────────────────────────

SEO_IRI = "http://senso-framework.org/ontology/seo#"
SEO_CONTEXT = {
    "@vocab": SEO_IRI,
    "seo": SEO_IRI,
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
}

BUG_FIX_KEYWORDS = [
    "fix", "bug", "defect", "patch", "repair", "resolve",
    "issue", "error", "fault", "failure", "crash", "exception",
    "hotfix", "hot-fix", "bugfix", "bug-fix", "regression",
    "correct", "workaround",
]

AGENT_COAUTHOR_PATTERNS = {
    "claude_code": [
        r"co-authored-by:.*claude.*@anthropic",
        r"co-authored-by:.*claude.*noreply",
    ],
    "copilot": [
        r"co-authored-by:.*copilot.*@github",
        r"co-authored-by:.*github-copilot",
    ],
    "codex": [
        r"co-authored-by:.*codex.*@openai",
    ],
}

AGENT_MESSAGE_PATTERNS = {
    "generic_agent": [
        r"generated by ai",
        r"ai-generated",
        r"auto-generated by",
    ],
    "claude_code": [r"generated by claude"],
    "codex": [r"generated by codex", r"codex agent"],
}


# ── Configuration ────────────────────────────────────────────────────────────

@dataclass
class PopulationConfig:
    """Configuration for the ontology population pipeline. Paper 1."""

    lookback_months: int = 36
    complexity_sample_months: int = 6
    fuseki_url: str = "http://localhost:3030"
    dataset: str = "seo"
    batch_size: int = 100
    ontology_iri: str = SEO_IRI
    owl_file: str = "ontology/modules/seo-full.owl"
    mann_kendall_alpha: float = 0.05
    clone_base_dir: str = ""
    github_token: str = ""

    @classmethod
    def from_yaml(cls, path: str) -> "PopulationConfig":
        """Load configuration from a YAML file."""
        with open(path) as f:
            data = yaml.safe_load(f) or {}
        flat = {}
        for section in data.values():
            if isinstance(section, dict):
                flat.update(section)
        return cls(**{k: v for k, v in flat.items() if k in cls.__dataclass_fields__})


# ── RepoMiner ────────────────────────────────────────────────────────────────

@dataclass
class CommitRecord:
    """Flat record for a single commit. Paper 1."""
    hash: str
    author_name: str
    author_email: str
    author_date: datetime
    message: str
    merge: bool
    insertions: int
    deletions: int
    files_changed: int
    modified_files: list  # list of dicts with path, complexity, nloc, added, removed
    is_bug_fix: bool
    is_agent_commit: bool
    agent_type: Optional[str]


class RepoMiner:
    """Wraps PyDriller to extract commit-level data for ontology population.

    Paper 1 — provides raw commit data that is subsequently mapped to
    SEO ontology classes (SoftwareProject, Commit, Version, File, Developer).
    """

    def __init__(self, config: PopulationConfig):
        self.config = config

    def mine(self, repo_url: str) -> list[CommitRecord]:
        """Mine commits from the last N months of a repository.

        Args:
            repo_url: GitHub URL (https://github.com/owner/name) or local path.

        Returns:
            List of CommitRecord objects sorted by author_date ascending.
        """
        from pydriller import Repository

        since = datetime.now(timezone.utc) - timedelta(
            days=self.config.lookback_months * 30
        )
        records: list[CommitRecord] = []
        count = 0

        logger.info("Mining %s (since %s)...", repo_url, since.strftime("%Y-%m-%d"))

        try:
            for commit in Repository(repo_url, since=since).traverse_commits():
                mod_files = []
                for mod in commit.modified_files:
                    mod_files.append({
                        "path": mod.new_path or mod.old_path,
                        "complexity": mod.complexity,
                        "nloc": mod.nloc,
                        "added": mod.added_lines,
                        "removed": mod.deleted_lines,
                        "change_type": mod.change_type.name if mod.change_type else None,
                    })

                msg_lower = (commit.msg or "").lower()
                is_bug = any(kw in msg_lower for kw in BUG_FIX_KEYWORDS)
                agent_type = self._detect_agent(commit)

                records.append(CommitRecord(
                    hash=commit.hash,
                    author_name=commit.author.name,
                    author_email=commit.author.email,
                    author_date=commit.author_date,
                    message=commit.msg or "",
                    merge=commit.merge,
                    insertions=commit.insertions,
                    deletions=commit.deletions,
                    files_changed=commit.files,
                    modified_files=mod_files,
                    is_bug_fix=is_bug,
                    is_agent_commit=agent_type is not None,
                    agent_type=agent_type,
                ))
                count += 1
                if count % 500 == 0:
                    logger.info("  Processed %d commits...", count)

        except Exception as exc:
            logger.error("Error mining %s: %s", repo_url, exc)

        logger.info("  Mined %d commits from %s", len(records), repo_url)
        return sorted(records, key=lambda r: r.author_date)

    @staticmethod
    def _detect_agent(commit) -> Optional[str]:
        """Detect agent involvement from commit metadata.

        Reuses logic from shared/mining/agent_detector.py.
        """
        msg = (commit.msg or "").lower()
        author = (commit.author.name or "").lower()

        # Co-author patterns
        for agent_type, patterns in AGENT_COAUTHOR_PATTERNS.items():
            for pattern in patterns:
                if re.search(pattern, msg):
                    return agent_type

        # Message patterns
        for agent_type, patterns in AGENT_MESSAGE_PATTERNS.items():
            for pattern in patterns:
                if re.search(pattern, msg):
                    return agent_type

        # Bot authors
        bot_names = ["[bot]", "codex", "devin"]
        if any(b in author for b in bot_names):
            return "bot"

        return None


# ── ComplexityAnalyzer ───────────────────────────────────────────────────────

@dataclass
class ComplexitySnapshot:
    """Monthly complexity snapshot for a repository. Paper 1."""
    month: str
    total_nloc: int
    total_ccn: float
    mean_ccn: float
    max_ccn: float
    function_count: int
    file_count: int


class ComplexityAnalyzer:
    """Wraps lizard for multi-language cyclomatic complexity analysis.

    Paper 1 — provides ComplexityMetric and SizeMetric instances for the
    SEO Metric Module. Runs lizard on cloned repository snapshots.
    """

    SUPPORTED_EXTENSIONS = {
        ".py", ".js", ".ts", ".java", ".c", ".cpp", ".h", ".hpp",
        ".cs", ".go", ".rb", ".rs", ".swift", ".kt", ".scala",
    }

    def __init__(self, config: PopulationConfig):
        self.config = config

    def analyze_working_tree(self, repo_path: str) -> Optional[ComplexitySnapshot]:
        """Run lizard on the current working tree of a repository.

        Args:
            repo_path: Local path to the cloned repository.

        Returns:
            ComplexitySnapshot for the current state, or None on failure.
        """
        import lizard

        try:
            analysis = lizard.analyze(
                paths=[repo_path],
                exts=lizard.get_extensions([]),
                threads=2,
            )

            total_nloc = 0
            total_ccn = 0.0
            max_ccn = 0.0
            func_count = 0
            files_seen = set()

            for file_info in analysis:
                files_seen.add(file_info.filename)
                for func in file_info.function_list:
                    total_nloc += func.nloc
                    total_ccn += func.cyclomatic_complexity
                    max_ccn = max(max_ccn, func.cyclomatic_complexity)
                    func_count += 1

            mean_ccn = total_ccn / max(func_count, 1)

            return ComplexitySnapshot(
                month=datetime.now(timezone.utc).strftime("%Y-%m"),
                total_nloc=total_nloc,
                total_ccn=total_ccn,
                mean_ccn=round(mean_ccn, 2),
                max_ccn=max_ccn,
                function_count=func_count,
                file_count=len(files_seen),
            )

        except Exception as exc:
            logger.error("Complexity analysis failed for %s: %s", repo_path, exc)
            return None

    def analyze_monthly_snapshots(
        self, repo_path: str, months: list[str]
    ) -> list[ComplexitySnapshot]:
        """Analyze complexity at monthly commit boundaries by checking out
        the last commit of each month.

        Args:
            repo_path: Local path to the cloned repository.
            months: List of month strings (YYYY-MM) to analyze.

        Returns:
            List of ComplexitySnapshot, one per successfully analyzed month.
        """
        snapshots: list[ComplexitySnapshot] = []

        for month in months:
            try:
                # Find last commit hash in this month
                result = subprocess.run(
                    ["git", "log", "--before", f"{month}-28",
                     "--after", f"{month}-01", "--format=%H", "-1"],
                    cwd=repo_path, capture_output=True, text=True, timeout=30,
                )
                commit_hash = result.stdout.strip()
                if not commit_hash:
                    continue

                # Checkout that commit
                subprocess.run(
                    ["git", "checkout", commit_hash, "--quiet"],
                    cwd=repo_path, capture_output=True, timeout=30,
                )

                snap = self.analyze_working_tree(repo_path)
                if snap:
                    snap.month = month
                    snapshots.append(snap)

            except Exception as exc:
                logger.warning("Snapshot failed for %s/%s: %s", repo_path, month, exc)

        # Return to default branch
        try:
            subprocess.run(
                ["git", "checkout", "-", "--quiet"],
                cwd=repo_path, capture_output=True, timeout=30,
            )
        except Exception:
            pass

        return snapshots


# ── DependencyParser ─────────────────────────────────────────────────────────

@dataclass
class DependencyInfo:
    """Parsed dependency information from package manifests. Paper 1."""
    manifest_type: str  # requirements_txt, package_json, pom_xml
    dependencies: list[dict]  # list of {name, version_spec, scope}
    dev_dependencies: list[dict]
    total_count: int


class DependencyParser:
    """Parses package manifests to extract dependency lists.

    Paper 1 — provides Dependency instances for the SEO Entity Module
    and data for Law VII (declining quality) conformance checking.
    """

    def parse_all(self, repo_path: str) -> list[DependencyInfo]:
        """Parse all recognized manifest files in a repository.

        Args:
            repo_path: Local path to the cloned repository.

        Returns:
            List of DependencyInfo, one per manifest found.
        """
        results: list[DependencyInfo] = []
        root = Path(repo_path)

        # requirements.txt
        req_file = root / "requirements.txt"
        if req_file.exists():
            try:
                results.append(self._parse_requirements_txt(req_file))
            except Exception as exc:
                logger.warning("Failed to parse requirements.txt: %s", exc)

        # package.json
        pkg_file = root / "package.json"
        if pkg_file.exists():
            try:
                results.append(self._parse_package_json(pkg_file))
            except Exception as exc:
                logger.warning("Failed to parse package.json: %s", exc)

        # pom.xml
        pom_file = root / "pom.xml"
        if pom_file.exists():
            try:
                results.append(self._parse_pom_xml(pom_file))
            except Exception as exc:
                logger.warning("Failed to parse pom.xml: %s", exc)

        return results

    @staticmethod
    def _parse_requirements_txt(path: Path) -> DependencyInfo:
        """Parse Python requirements.txt."""
        deps: list[dict] = []
        for line in path.read_text(errors="replace").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("-"):
                continue
            # Handle name==version, name>=version, name, etc.
            match = re.match(r"^([A-Za-z0-9_.-]+)\s*([><=!~]+.+)?", line)
            if match:
                deps.append({
                    "name": match.group(1),
                    "version_spec": (match.group(2) or "").strip(),
                    "scope": "runtime",
                })
        return DependencyInfo(
            manifest_type="requirements_txt",
            dependencies=deps,
            dev_dependencies=[],
            total_count=len(deps),
        )

    @staticmethod
    def _parse_package_json(path: Path) -> DependencyInfo:
        """Parse Node.js package.json."""
        data = json.loads(path.read_text(errors="replace"))
        deps = [
            {"name": k, "version_spec": v, "scope": "runtime"}
            for k, v in (data.get("dependencies") or {}).items()
        ]
        dev_deps = [
            {"name": k, "version_spec": v, "scope": "dev"}
            for k, v in (data.get("devDependencies") or {}).items()
        ]
        return DependencyInfo(
            manifest_type="package_json",
            dependencies=deps,
            dev_dependencies=dev_deps,
            total_count=len(deps) + len(dev_deps),
        )

    @staticmethod
    def _parse_pom_xml(path: Path) -> DependencyInfo:
        """Parse Maven pom.xml."""
        ns = {"m": "http://maven.apache.org/POM/4.0.0"}
        tree = ElementTree.parse(path)
        root = tree.getroot()

        deps: list[dict] = []
        dev_deps: list[dict] = []

        for dep_elem in root.findall(".//m:dependencies/m:dependency", ns):
            group = dep_elem.findtext("m:groupId", "", ns)
            artifact = dep_elem.findtext("m:artifactId", "", ns)
            version = dep_elem.findtext("m:version", "", ns)
            scope = dep_elem.findtext("m:scope", "compile", ns)

            entry = {
                "name": f"{group}:{artifact}",
                "version_spec": version,
                "scope": scope,
            }
            if scope == "test":
                dev_deps.append(entry)
            else:
                deps.append(entry)

        return DependencyInfo(
            manifest_type="pom_xml",
            dependencies=deps,
            dev_dependencies=dev_deps,
            total_count=len(deps) + len(dev_deps),
        )


# ── PhaseDetector ────────────────────────────────────────────────────────────

@dataclass
class PhaseLabel:
    """Evolution phase label computed via Mann-Kendall trend test. Paper 1."""
    phase: str  # "growth", "stabilization", "decline"
    trend: str  # "increasing", "no trend", "decreasing"
    p_value: float
    tau: float  # Kendall's tau
    slope: float  # Sen's slope
    start_month: str
    end_month: str


class PhaseDetector:
    """Detects evolution phase via Mann-Kendall trend test on LOC time series.

    Paper 1 — produces GrowthPhase / StabilizationPhase / DeclinePhase
    instances for the SEO Evolution Process Module. Also used for RQ1
    convergent validity (ontology phase labels vs. statistical phase labels).
    """

    def __init__(self, alpha: float = 0.05):
        self.alpha = alpha

    def detect(self, monthly_loc: list[tuple[str, int]]) -> Optional[PhaseLabel]:
        """Run Mann-Kendall trend test on monthly LOC time series.

        Args:
            monthly_loc: List of (month_str, total_loc) tuples, sorted chronologically.

        Returns:
            PhaseLabel or None if insufficient data.
        """
        if len(monthly_loc) < 4:
            logger.warning(
                "Insufficient data for Mann-Kendall test (%d months)", len(monthly_loc)
            )
            return None

        import pymannkendall as mk

        months = [m for m, _ in monthly_loc]
        values = [v for _, v in monthly_loc]

        try:
            result = mk.original_test(values, alpha=self.alpha)
        except Exception as exc:
            logger.error("Mann-Kendall test failed: %s", exc)
            return None

        # Map trend to phase
        if result.trend == "increasing":
            phase = "growth"
        elif result.trend == "decreasing":
            phase = "decline"
        else:
            phase = "stabilization"

        return PhaseLabel(
            phase=phase,
            trend=result.trend,
            p_value=result.p,
            tau=result.Tau,
            slope=result.slope,
            start_month=months[0],
            end_month=months[-1],
        )


# ── LawConformanceChecker ────────────────────────────────────────────────────

@dataclass
class LawConformance:
    """Conformance assessment for one of Lehman's 8 laws. Paper 1."""
    law_number: int
    law_name: str
    conforms: bool
    evidence: str
    metric_value: Optional[float] = None


class LawConformanceChecker:
    """Checks each of Lehman's 8 laws against mined repository data.

    Paper 1 — produces LawConformance instances mapped to the SEO
    Evolution Law Module. Each law is operationalized as a testable
    condition on the mined monthly metrics.
    """

    LAW_NAMES = {
        1: "Continuing Change",
        2: "Increasing Complexity",
        3: "Self Regulation",
        4: "Conservation of Organizational Stability",
        5: "Conservation of Familiarity",
        6: "Continuing Growth",
        7: "Declining Quality",
        8: "Feedback System",
    }

    def check_all(
        self,
        monthly_metrics: list[dict],
        phase: Optional[PhaseLabel],
    ) -> list[LawConformance]:
        """Check all 8 Lehman's laws against monthly metric data.

        Args:
            monthly_metrics: List of monthly metric dicts (from aggregation).
            phase: Detected phase label (from PhaseDetector).

        Returns:
            List of LawConformance, one per law.
        """
        results = [
            self._check_law_1(monthly_metrics),
            self._check_law_2(monthly_metrics),
            self._check_law_3(monthly_metrics),
            self._check_law_4(monthly_metrics),
            self._check_law_5(monthly_metrics),
            self._check_law_6(monthly_metrics, phase),
            self._check_law_7(monthly_metrics),
            self._check_law_8(monthly_metrics),
        ]
        return results

    def _check_law_1(self, metrics: list[dict]) -> LawConformance:
        """Law I — Continuing Change: system must be continually adapted."""
        if len(metrics) < 2:
            return LawConformance(1, self.LAW_NAMES[1], False,
                                  "Insufficient data", None)
        # Active months (>0 commits) vs. total months
        active = sum(1 for m in metrics if m.get("commit_count", 0) > 0)
        ratio = active / len(metrics)
        conforms = ratio >= 0.5
        return LawConformance(
            1, self.LAW_NAMES[1], conforms,
            f"{active}/{len(metrics)} months active ({ratio:.1%})",
            ratio,
        )

    def _check_law_2(self, metrics: list[dict]) -> LawConformance:
        """Law II — Increasing Complexity: complexity increases unless
        work is done to reduce it."""
        complexities = [
            m["complexity_mean"] for m in metrics
            if m.get("complexity_mean") is not None and m["complexity_mean"] > 0
        ]
        if len(complexities) < 3:
            return LawConformance(2, self.LAW_NAMES[2], False,
                                  "Insufficient complexity data", None)
        first_half = complexities[: len(complexities) // 2]
        second_half = complexities[len(complexities) // 2:]
        avg_first = sum(first_half) / len(first_half)
        avg_second = sum(second_half) / len(second_half)
        increasing = avg_second >= avg_first
        delta = ((avg_second - avg_first) / max(avg_first, 0.01)) * 100
        return LawConformance(
            2, self.LAW_NAMES[2], increasing,
            f"Complexity {'increased' if increasing else 'decreased'} "
            f"{abs(delta):.1f}% (first half avg={avg_first:.2f}, "
            f"second half avg={avg_second:.2f})",
            delta,
        )

    def _check_law_3(self, metrics: list[dict]) -> LawConformance:
        """Law III — Self Regulation: evolution process is self-regulating
        (growth rate statistically invariant)."""
        if len(metrics) < 6:
            return LawConformance(3, self.LAW_NAMES[3], False,
                                  "Insufficient data", None)
        sizes = [m.get("total_churn", 0) for m in metrics]
        mean_churn = sum(sizes) / len(sizes)
        variance = sum((s - mean_churn) ** 2 for s in sizes) / len(sizes)
        std_dev = variance ** 0.5
        cv = std_dev / max(mean_churn, 1)
        # Self-regulation: coefficient of variation is moderate (< 2.0)
        conforms = cv < 2.0
        return LawConformance(
            3, self.LAW_NAMES[3], conforms,
            f"Churn CV={cv:.2f} (mean={mean_churn:.0f}, std={std_dev:.0f})",
            cv,
        )

    def _check_law_4(self, metrics: list[dict]) -> LawConformance:
        """Law IV — Conservation of Organizational Stability: average
        effective global activity rate is statistically invariant."""
        if len(metrics) < 6:
            return LawConformance(4, self.LAW_NAMES[4], False,
                                  "Insufficient data", None)
        commit_rates = [m.get("commit_count", 0) for m in metrics]
        mean_rate = sum(commit_rates) / len(commit_rates)
        variance = sum((r - mean_rate) ** 2 for r in commit_rates) / len(commit_rates)
        std_dev = variance ** 0.5
        cv = std_dev / max(mean_rate, 1)
        conforms = cv < 1.5
        return LawConformance(
            4, self.LAW_NAMES[4], conforms,
            f"Commit rate CV={cv:.2f} (mean={mean_rate:.1f}/month)",
            cv,
        )

    def _check_law_5(self, metrics: list[dict]) -> LawConformance:
        """Law V — Conservation of Familiarity: incremental growth is
        approximately constant."""
        if len(metrics) < 4:
            return LawConformance(5, self.LAW_NAMES[5], False,
                                  "Insufficient data", None)
        increments = [m.get("lines_added", 0) for m in metrics]
        mean_inc = sum(increments) / len(increments)
        variance = sum((i - mean_inc) ** 2 for i in increments) / len(increments)
        std_dev = variance ** 0.5
        cv = std_dev / max(mean_inc, 1)
        conforms = cv < 2.0
        return LawConformance(
            5, self.LAW_NAMES[5], conforms,
            f"Addition rate CV={cv:.2f} (mean={mean_inc:.0f} lines/month)",
            cv,
        )

    def _check_law_6(
        self, metrics: list[dict], phase: Optional[PhaseLabel]
    ) -> LawConformance:
        """Law VI — Continuing Growth: functional content must be
        continually increased to maintain user satisfaction."""
        if phase is None:
            return LawConformance(6, self.LAW_NAMES[6], False,
                                  "No phase data available", None)
        conforms = phase.phase in ("growth", "stabilization")
        return LawConformance(
            6, self.LAW_NAMES[6], conforms,
            f"Phase={phase.phase} (tau={phase.tau:.3f}, slope={phase.slope:.1f})",
            phase.slope,
        )

    def _check_law_7(self, metrics: list[dict]) -> LawConformance:
        """Law VII — Declining Quality: quality will appear to be
        declining unless rigorously maintained."""
        bug_ratios = [
            m.get("bug_fix_ratio", 0) for m in metrics
            if m.get("commit_count", 0) > 0
        ]
        if len(bug_ratios) < 4:
            return LawConformance(7, self.LAW_NAMES[7], False,
                                  "Insufficient data", None)
        first_half = bug_ratios[: len(bug_ratios) // 2]
        second_half = bug_ratios[len(bug_ratios) // 2:]
        avg_first = sum(first_half) / len(first_half)
        avg_second = sum(second_half) / len(second_half)
        # Law conforms if bug ratio is increasing or stable (quality declining)
        conforms = avg_second >= avg_first * 0.9  # 10% tolerance
        return LawConformance(
            7, self.LAW_NAMES[7], conforms,
            f"Bug-fix ratio first={avg_first:.2%}, second={avg_second:.2%}",
            avg_second - avg_first,
        )

    def _check_law_8(self, metrics: list[dict]) -> LawConformance:
        """Law VIII — Feedback System: evolution is a multi-level,
        multi-loop feedback system."""
        if len(metrics) < 6:
            return LawConformance(8, self.LAW_NAMES[8], False,
                                  "Insufficient data", None)
        # Evidence of feedback: merge ratio > 0 (code review), multi-author
        merge_months = sum(
            1 for m in metrics if m.get("merge_ratio", 0) > 0
        )
        multi_author = sum(
            1 for m in metrics if m.get("unique_authors", 0) > 1
        )
        total = len(metrics)
        conforms = (merge_months / total > 0.3) and (multi_author / total > 0.3)
        return LawConformance(
            8, self.LAW_NAMES[8], conforms,
            f"Merge months: {merge_months}/{total}, "
            f"Multi-author months: {multi_author}/{total}",
            merge_months / total,
        )


# ── Agent Adoption Detector ─────────────────────────────────────────────────

def detect_agent_adoption_date(commits: list[CommitRecord]) -> Optional[str]:
    """Find the earliest agent commit to determine adoption date.

    Reuses detection logic from shared/mining/agent_detector.py.
    Paper 1 — produces AgentAdoptionEvent for the SEO Process Module.

    Args:
        commits: List of CommitRecord objects.

    Returns:
        ISO date string of earliest agent commit, or None.
    """
    agent_commits = [c for c in commits if c.is_agent_commit]
    if not agent_commits:
        return None
    earliest = min(agent_commits, key=lambda c: c.author_date)
    return earliest.author_date.isoformat()


# ── Monthly Metrics Aggregation ──────────────────────────────────────────────

def aggregate_monthly(commits: list[CommitRecord]) -> list[dict]:
    """Aggregate commits into monthly metric dictionaries.

    Paper 1 — intermediate step before JSON-LD mapping.

    Args:
        commits: Sorted list of CommitRecord objects.

    Returns:
        List of monthly metric dicts, sorted chronologically.
    """
    monthly: dict[str, dict] = defaultdict(lambda: {
        "commit_count": 0,
        "merge_count": 0,
        "authors": set(),
        "lines_added": 0,
        "lines_deleted": 0,
        "files_changed": 0,
        "bug_fix_count": 0,
        "agent_commit_count": 0,
        "agent_lines_added": 0,
        "file_complexities": {},
        "file_nlocs": {},
    })

    for c in commits:
        month = c.author_date.strftime("%Y-%m")
        m = monthly[month]
        m["commit_count"] += 1
        if c.merge:
            m["merge_count"] += 1
        m["authors"].add(c.author_email)
        m["lines_added"] += c.insertions
        m["lines_deleted"] += c.deletions
        m["files_changed"] += c.files_changed
        if c.is_bug_fix:
            m["bug_fix_count"] += 1
        if c.is_agent_commit:
            m["agent_commit_count"] += 1
            m["agent_lines_added"] += c.insertions

        for mf in c.modified_files:
            path = mf.get("path")
            if path and mf.get("complexity") is not None:
                m["file_complexities"][path] = mf["complexity"]
            if path and mf.get("nloc") is not None:
                m["file_nlocs"][path] = mf["nloc"]

    results = []
    for month in sorted(monthly.keys()):
        m = monthly[month]
        cc = max(m["commit_count"], 1)
        complexities = list(m["file_complexities"].values()) or [0]
        nlocs = list(m["file_nlocs"].values()) or [0]

        results.append({
            "month": month,
            "commit_count": m["commit_count"],
            "merge_count": m["merge_count"],
            "unique_authors": len(m["authors"]),
            "lines_added": m["lines_added"],
            "lines_deleted": m["lines_deleted"],
            "total_churn": m["lines_added"] + m["lines_deleted"],
            "files_changed": m["files_changed"],
            "bug_fix_count": m["bug_fix_count"],
            "bug_fix_ratio": m["bug_fix_count"] / cc,
            "merge_ratio": m["merge_count"] / cc,
            "agent_commit_count": m["agent_commit_count"],
            "agent_commit_ratio": m["agent_commit_count"] / cc,
            "agent_lines_ratio": (
                m["agent_lines_added"] / max(m["lines_added"], 1)
            ),
            "complexity_mean": sum(complexities) / len(complexities),
            "complexity_max": max(complexities),
            "nloc_total": sum(nlocs),
        })

    return results


# ── JSON-LD Mapping ──────────────────────────────────────────────────────────

def _mint_uri(class_name: str, identifier: str) -> str:
    """Mint a deterministic URI for an ontology individual."""
    safe_id = re.sub(r"[^A-Za-z0-9_.-]", "_", identifier)
    return f"{SEO_IRI}{class_name}_{safe_id}"


class OntologyPopulator:
    """Maps extracted repository data to SEO ontology instances in JSON-LD
    and loads them into Apache Jena Fuseki.

    Paper 1 — core population pipeline. Produces individuals for all five
    SEO modules: Entity, Process, Metric, Law, and Pattern.
    """

    def __init__(self, config: PopulationConfig):
        self.config = config
        self.triples: list[dict] = []

    def build_jsonld(
        self,
        repo_name: str,
        commits: list[CommitRecord],
        monthly_metrics: list[dict],
        complexity_snapshots: list[ComplexitySnapshot],
        dependencies: list[DependencyInfo],
        phase: Optional[PhaseLabel],
        law_conformance: list[LawConformance],
        agent_adoption_date: Optional[str],
    ) -> dict:
        """Build a JSON-LD document representing the full ontology population
        for a single repository.

        Args:
            repo_name: Repository identifier (owner/name).
            commits: Mined commit records.
            monthly_metrics: Aggregated monthly metrics.
            complexity_snapshots: Lizard complexity snapshots.
            dependencies: Parsed dependency information.
            phase: Detected evolution phase label.
            law_conformance: Law conformance results.
            agent_adoption_date: ISO date of agent adoption (or None).

        Returns:
            JSON-LD dict ready for triple generation.
        """
        project_uri = _mint_uri("SoftwareProject", repo_name)
        graph: list[dict] = []

        # ── SoftwareProject ──
        project_node = {
            "@id": project_uri,
            "@type": "seo:SoftwareProject",
            "seo:name": repo_name,
            "seo:totalCommits": len(commits),
            "seo:monthsTracked": len(monthly_metrics),
        }
        if agent_adoption_date:
            project_node["seo:agentAdoptionDate"] = {
                "@type": "xsd:dateTime",
                "@value": agent_adoption_date,
            }
        graph.append(project_node)

        # ── Developers ──
        authors_seen: set[str] = set()
        for c in commits:
            if c.author_email not in authors_seen:
                authors_seen.add(c.author_email)
                dev_uri = _mint_uri("Developer", c.author_email)
                graph.append({
                    "@id": dev_uri,
                    "@type": "seo:Developer",
                    "seo:name": c.author_name,
                    "seo:email": c.author_email,
                    "seo:contributesTo": {"@id": project_uri},
                })

        # ── Monthly Versions ──
        prev_version_uri = None
        for mm in monthly_metrics:
            version_uri = _mint_uri("Version", f"{repo_name}_{mm['month']}")
            version_node = {
                "@id": version_uri,
                "@type": "seo:Version",
                "seo:month": mm["month"],
                "seo:commitCount": mm["commit_count"],
                "seo:uniqueAuthors": mm["unique_authors"],
                "seo:linesAdded": mm["lines_added"],
                "seo:linesDeleted": mm["lines_deleted"],
                "seo:totalChurn": mm["total_churn"],
                "seo:filesChanged": mm["files_changed"],
                "seo:bugFixCount": mm["bug_fix_count"],
                "seo:bugFixRatio": mm["bug_fix_ratio"],
                "seo:agentCommitCount": mm["agent_commit_count"],
                "seo:agentCommitRatio": mm["agent_commit_ratio"],
                "seo:belongsToProject": {"@id": project_uri},
            }
            if prev_version_uri:
                version_node["seo:succeeds"] = {"@id": prev_version_uri}
            graph.append(version_node)
            prev_version_uri = version_uri

            # ── Metrics per version ──
            metric_uri = _mint_uri("ComplexityMetric", f"{repo_name}_{mm['month']}")
            graph.append({
                "@id": metric_uri,
                "@type": "seo:ComplexityMetric",
                "seo:meanCyclomaticComplexity": mm["complexity_mean"],
                "seo:maxCyclomaticComplexity": mm["complexity_max"],
                "seo:measuredForVersion": {"@id": version_uri},
            })

            size_uri = _mint_uri("SizeMetric", f"{repo_name}_{mm['month']}")
            graph.append({
                "@id": size_uri,
                "@type": "seo:SizeMetric",
                "seo:totalNLOC": mm["nloc_total"],
                "seo:measuredForVersion": {"@id": version_uri},
            })

            activity_uri = _mint_uri("ActivityMetric", f"{repo_name}_{mm['month']}")
            graph.append({
                "@id": activity_uri,
                "@type": "seo:ActivityMetric",
                "seo:commitCount": mm["commit_count"],
                "seo:uniqueAuthors": mm["unique_authors"],
                "seo:mergeRatio": mm["merge_ratio"],
                "seo:measuredForVersion": {"@id": version_uri},
            })

        # ── Complexity Snapshots (from lizard) ──
        for snap in complexity_snapshots:
            snap_uri = _mint_uri("ComplexitySnapshot", f"{repo_name}_{snap.month}")
            graph.append({
                "@id": snap_uri,
                "@type": "seo:ComplexityMetric",
                "seo:totalNLOC": snap.total_nloc,
                "seo:totalCyclomaticComplexity": snap.total_ccn,
                "seo:meanCyclomaticComplexity": snap.mean_ccn,
                "seo:maxCyclomaticComplexity": snap.max_ccn,
                "seo:functionCount": snap.function_count,
                "seo:fileCount": snap.file_count,
                "seo:month": snap.month,
                "seo:belongsToProject": {"@id": project_uri},
            })

        # ── Dependencies ──
        for dep_info in dependencies:
            for dep in dep_info.dependencies + dep_info.dev_dependencies:
                dep_uri = _mint_uri(
                    "Dependency", f"{repo_name}_{dep['name']}"
                )
                graph.append({
                    "@id": dep_uri,
                    "@type": "seo:Dependency",
                    "seo:dependencyName": dep["name"],
                    "seo:versionSpec": dep.get("version_spec", ""),
                    "seo:scope": dep.get("scope", "runtime"),
                    "seo:manifestType": dep_info.manifest_type,
                    "seo:dependencyOf": {"@id": project_uri},
                })

        # ── Evolution Phase ──
        if phase:
            phase_type_map = {
                "growth": "seo:GrowthPhase",
                "stabilization": "seo:StabilizationPhase",
                "decline": "seo:DeclinePhase",
            }
            phase_uri = _mint_uri("EvolutionPhase", repo_name)
            graph.append({
                "@id": phase_uri,
                "@type": phase_type_map.get(phase.phase, "seo:EvolutionEpisode"),
                "seo:phaseName": phase.phase,
                "seo:trend": phase.trend,
                "seo:pValue": phase.p_value,
                "seo:kendallTau": phase.tau,
                "seo:senSlope": phase.slope,
                "seo:startMonth": phase.start_month,
                "seo:endMonth": phase.end_month,
                "seo:phaseOf": {"@id": project_uri},
            })

        # ── Law Conformance ──
        for lc in law_conformance:
            law_uri = _mint_uri(
                "LawConformance", f"{repo_name}_law{lc.law_number}"
            )
            graph.append({
                "@id": law_uri,
                "@type": "seo:LawConformance",
                "seo:lawNumber": lc.law_number,
                "seo:lawName": lc.law_name,
                "seo:conforms": lc.conforms,
                "seo:evidence": lc.evidence,
                "seo:metricValue": lc.metric_value,
                "seo:assessedFor": {"@id": project_uri},
            })

        # ── Agent Adoption Event ──
        if agent_adoption_date:
            event_uri = _mint_uri("AgentAdoptionEvent", repo_name)
            graph.append({
                "@id": event_uri,
                "@type": "seo:AgentAdoptionEvent",
                "seo:adoptionDate": {
                    "@type": "xsd:dateTime",
                    "@value": agent_adoption_date,
                },
                "seo:eventOf": {"@id": project_uri},
            })

        # ── Agent Commits (sample up to 200 for tractability) ──
        agent_commits = [c for c in commits if c.is_agent_commit][:200]
        for ac in agent_commits:
            ac_uri = _mint_uri("AgentCommit", ac.hash[:12])
            graph.append({
                "@id": ac_uri,
                "@type": "seo:AgentCommit",
                "seo:commitHash": ac.hash,
                "seo:agentType": ac.agent_type or "unknown",
                "seo:authorDate": {
                    "@type": "xsd:dateTime",
                    "@value": ac.author_date.isoformat(),
                },
                "seo:insertions": ac.insertions,
                "seo:deletions": ac.deletions,
                "seo:commitOf": {"@id": project_uri},
            })

        doc = {
            "@context": SEO_CONTEXT,
            "@graph": graph,
        }

        logger.info(
            "Built JSON-LD for %s: %d graph nodes", repo_name, len(graph)
        )
        return doc

    def jsonld_to_ntriples(self, doc: dict) -> list[str]:
        """Convert JSON-LD graph nodes to N-Triples strings for SPARQL INSERT.

        This is a simplified serializer that handles the flat JSON-LD structure
        produced by build_jsonld. For production use, consider rdflib's JSON-LD
        plugin.

        Args:
            doc: JSON-LD document with @context and @graph.

        Returns:
            List of N-Triple strings.
        """
        triples: list[str] = []

        for node in doc.get("@graph", []):
            subj = node.get("@id", "")
            if not subj:
                continue
            subj_nt = f"<{subj}>"

            # rdf:type
            rdf_type = node.get("@type", "")
            if rdf_type:
                type_uri = rdf_type.replace("seo:", SEO_IRI)
                triples.append(
                    f'{subj_nt} <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> '
                    f'<{type_uri}> .'
                )

            for key, val in node.items():
                if key in ("@id", "@type"):
                    continue

                pred_uri = key.replace("seo:", SEO_IRI)
                pred_uri = pred_uri.replace("rdfs:", "http://www.w3.org/2000/01/rdf-schema#")
                pred_uri = pred_uri.replace("xsd:", "http://www.w3.org/2001/XMLSchema#")
                pred_nt = f"<{pred_uri}>"

                if isinstance(val, dict):
                    if "@id" in val:
                        triples.append(f'{subj_nt} {pred_nt} <{val["@id"]}> .')
                    elif "@value" in val:
                        dtype = val.get("@type", "").replace(
                            "xsd:", "http://www.w3.org/2001/XMLSchema#"
                        )
                        escaped = str(val["@value"]).replace("\\", "\\\\").replace('"', '\\"')
                        if dtype:
                            triples.append(
                                f'{subj_nt} {pred_nt} "{escaped}"^^<{dtype}> .'
                            )
                        else:
                            triples.append(f'{subj_nt} {pred_nt} "{escaped}" .')
                elif isinstance(val, bool):
                    val_str = "true" if val else "false"
                    triples.append(
                        f'{subj_nt} {pred_nt} "{val_str}"'
                        f'^^<http://www.w3.org/2001/XMLSchema#boolean> .'
                    )
                elif isinstance(val, int):
                    triples.append(
                        f'{subj_nt} {pred_nt} "{val}"'
                        f'^^<http://www.w3.org/2001/XMLSchema#integer> .'
                    )
                elif isinstance(val, float):
                    triples.append(
                        f'{subj_nt} {pred_nt} "{val}"'
                        f'^^<http://www.w3.org/2001/XMLSchema#double> .'
                    )
                elif isinstance(val, str):
                    escaped = val.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
                    triples.append(
                        f'{subj_nt} {pred_nt} "{escaped}"'
                        f'^^<http://www.w3.org/2001/XMLSchema#string> .'
                    )

        return triples


# ── FusekiLoader ─────────────────────────────────────────────────────────────

class FusekiLoader:
    """Loads triples into Apache Jena Fuseki via SPARQL INSERT DATA.

    Paper 1 — final step of the population pipeline. Batches triples
    for efficiency (default 100 per INSERT).
    """

    def __init__(self, fuseki_url: str, dataset: str, batch_size: int = 100):
        self.endpoint = f"{fuseki_url}/{dataset}/update"
        self.query_endpoint = f"{fuseki_url}/{dataset}/sparql"
        self.batch_size = batch_size

    def load_triples(self, triples: list[str]) -> int:
        """Load N-Triple strings into Fuseki via batched SPARQL INSERT DATA.

        Args:
            triples: List of N-Triple strings.

        Returns:
            Number of triples successfully loaded.
        """
        from SPARQLWrapper import SPARQLWrapper, POST

        sparql = SPARQLWrapper(self.endpoint)
        sparql.setMethod(POST)

        loaded = 0
        total_batches = (len(triples) + self.batch_size - 1) // self.batch_size

        for i in range(0, len(triples), self.batch_size):
            batch = triples[i: i + self.batch_size]
            batch_num = (i // self.batch_size) + 1
            data_block = "\n".join(batch)
            query = f"INSERT DATA {{\n{data_block}\n}}"

            try:
                sparql.setQuery(query)
                sparql.query()
                loaded += len(batch)
                if batch_num % 10 == 0 or batch_num == total_batches:
                    logger.info(
                        "  Loaded batch %d/%d (%d triples)",
                        batch_num, total_batches, loaded,
                    )
            except Exception as exc:
                logger.error(
                    "  Failed to load batch %d/%d: %s", batch_num, total_batches, exc
                )

        logger.info("Loaded %d/%d triples into Fuseki", loaded, len(triples))
        return loaded

    def count_triples(self) -> int:
        """Return the total number of triples in the dataset."""
        from SPARQLWrapper import SPARQLWrapper, JSON

        sparql = SPARQLWrapper(self.query_endpoint)
        sparql.setQuery("SELECT (COUNT(*) AS ?count) WHERE { ?s ?p ?o }")
        sparql.setReturnFormat(JSON)
        try:
            results = sparql.query().convert()
            return int(
                results["results"]["bindings"][0]["count"]["value"]
            )
        except Exception as exc:
            logger.error("Failed to count triples: %s", exc)
            return -1


# ── ConsistencyChecker ───────────────────────────────────────────────────────

class ConsistencyChecker:
    """Runs HermiT consistency check on the populated ontology via Owlready2.

    Paper 1 — validates that populated individuals do not violate OWL 2 DL
    axioms defined in the SEO ontology modules.
    """

    def __init__(self, owl_file: str):
        self.owl_file = owl_file

    def check(self) -> dict:
        """Run HermiT reasoner and return consistency results.

        Returns:
            Dict with keys: consistent (bool), errors (list), individuals (int).
        """
        try:
            import owlready2

            onto = owlready2.get_ontology(f"file://{self.owl_file}").load()
            individuals_before = len(list(onto.individuals()))

            try:
                owlready2.sync_reasoner_hermit(onto, infer_property_values=True)
                inconsistent = list(owlready2.default_world.inconsistent_classes())
                consistent = len(inconsistent) == 0
                errors = [str(c) for c in inconsistent]
            except Exception as exc:
                consistent = False
                errors = [str(exc)]

            return {
                "consistent": consistent,
                "errors": errors,
                "individuals": individuals_before,
                "owl_file": self.owl_file,
            }

        except ImportError:
            logger.warning(
                "Owlready2 not installed — skipping consistency check"
            )
            return {
                "consistent": None,
                "errors": ["owlready2 not available"],
                "individuals": 0,
                "owl_file": self.owl_file,
            }
        except Exception as exc:
            logger.error("Consistency check failed: %s", exc)
            return {
                "consistent": False,
                "errors": [str(exc)],
                "individuals": 0,
                "owl_file": self.owl_file,
            }


# ── Clone Helper ─────────────────────────────────────────────────────────────

def clone_repo(repo_name: str, base_dir: str = "") -> Optional[str]:
    """Clone a GitHub repository to a temporary directory.

    Args:
        repo_name: Repository in owner/name format.
        base_dir: Base directory for clones. Uses tempdir if empty.

    Returns:
        Path to the cloned repository, or None on failure.
    """
    url = f"https://github.com/{repo_name}.git"
    if base_dir:
        clone_dir = os.path.join(base_dir, repo_name.replace("/", "__"))
    else:
        clone_dir = os.path.join(
            tempfile.gettempdir(), "senso_clones", repo_name.replace("/", "__")
        )

    if os.path.isdir(os.path.join(clone_dir, ".git")):
        logger.info("Repository already cloned at %s, pulling...", clone_dir)
        try:
            subprocess.run(
                ["git", "pull", "--quiet"],
                cwd=clone_dir, capture_output=True, timeout=120,
            )
            return clone_dir
        except Exception as exc:
            logger.warning("Pull failed, re-cloning: %s", exc)

    os.makedirs(os.path.dirname(clone_dir), exist_ok=True)
    logger.info("Cloning %s to %s...", url, clone_dir)
    try:
        subprocess.run(
            ["git", "clone", "--quiet", url, clone_dir],
            capture_output=True, timeout=600, check=True,
        )
        return clone_dir
    except subprocess.CalledProcessError as exc:
        logger.error("Clone failed for %s: %s", repo_name, exc.stderr)
        return None
    except Exception as exc:
        logger.error("Clone failed for %s: %s", repo_name, exc)
        return None


# ── Pipeline Orchestration ───────────────────────────────────────────────────

def populate_repo(repo_name: str, config: PopulationConfig) -> dict:
    """Run the full population pipeline for a single repository.

    Paper 1 — orchestrates all pipeline stages: mine, analyze, parse,
    detect phase, check laws, build JSON-LD, load into Fuseki, check
    consistency.

    Args:
        repo_name: Repository in owner/name format.
        config: Population configuration.

    Returns:
        Summary dict with pipeline results and statistics.
    """
    summary: dict[str, Any] = {
        "repo": repo_name,
        "status": "started",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    # ── Step 1: Mine commits ──
    logger.info("=== Populating %s ===", repo_name)
    repo_url = f"https://github.com/{repo_name}"
    miner = RepoMiner(config)
    commits = miner.mine(repo_url)

    if not commits:
        summary["status"] = "failed"
        summary["error"] = "No commits mined"
        logger.error("No commits found for %s", repo_name)
        return summary

    summary["total_commits"] = len(commits)

    # ── Step 2: Aggregate monthly metrics ──
    monthly_metrics = aggregate_monthly(commits)
    summary["total_months"] = len(monthly_metrics)

    # ── Step 3: Complexity analysis (optional, requires clone) ──
    complexity_snapshots: list[ComplexitySnapshot] = []
    clone_path = clone_repo(repo_name, config.clone_base_dir)
    if clone_path:
        analyzer = ComplexityAnalyzer(config)
        # Analyze last N months
        recent_months = [
            m["month"] for m in monthly_metrics[-config.complexity_sample_months:]
        ]
        complexity_snapshots = analyzer.analyze_monthly_snapshots(
            clone_path, recent_months
        )
        summary["complexity_snapshots"] = len(complexity_snapshots)

    # ── Step 4: Parse dependencies ──
    dependencies: list[DependencyInfo] = []
    if clone_path:
        parser = DependencyParser()
        dependencies = parser.parse_all(clone_path)
        summary["dependency_manifests"] = len(dependencies)
        summary["total_dependencies"] = sum(d.total_count for d in dependencies)

    # ── Step 5: Detect phase ──
    monthly_loc = [
        (m["month"], m["nloc_total"]) for m in monthly_metrics
        if m.get("nloc_total", 0) > 0
    ]
    phase_detector = PhaseDetector(alpha=config.mann_kendall_alpha)
    phase = phase_detector.detect(monthly_loc)
    if phase:
        summary["phase"] = phase.phase
        summary["phase_p_value"] = phase.p_value
    else:
        summary["phase"] = "unknown"

    # ── Step 6: Check Lehman's laws ──
    law_checker = LawConformanceChecker()
    law_conformance = law_checker.check_all(monthly_metrics, phase)
    summary["law_conformance"] = {
        f"law_{lc.law_number}": lc.conforms for lc in law_conformance
    }

    # ── Step 7: Detect agent adoption ──
    agent_adoption_date = detect_agent_adoption_date(commits)
    summary["agent_adoption_date"] = agent_adoption_date

    # ── Step 8: Build JSON-LD ──
    populator = OntologyPopulator(config)
    jsonld_doc = populator.build_jsonld(
        repo_name=repo_name,
        commits=commits,
        monthly_metrics=monthly_metrics,
        complexity_snapshots=complexity_snapshots,
        dependencies=dependencies,
        phase=phase,
        law_conformance=law_conformance,
        agent_adoption_date=agent_adoption_date,
    )
    summary["jsonld_nodes"] = len(jsonld_doc.get("@graph", []))

    # ── Step 9: Convert to triples ──
    triples = populator.jsonld_to_ntriples(jsonld_doc)
    summary["total_triples"] = len(triples)

    # ── Step 10: Load into Fuseki ──
    try:
        loader = FusekiLoader(
            config.fuseki_url, config.dataset, config.batch_size
        )
        loaded = loader.load_triples(triples)
        summary["triples_loaded"] = loaded
        summary["fuseki_total"] = loader.count_triples()
    except Exception as exc:
        logger.error("Fuseki loading failed: %s", exc)
        summary["triples_loaded"] = 0
        summary["fuseki_error"] = str(exc)

    # ── Step 11: Consistency check ──
    owl_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        config.owl_file,
    )
    if os.path.isfile(owl_path):
        checker = ConsistencyChecker(owl_path)
        consistency = checker.check()
        summary["consistency"] = consistency
    else:
        logger.warning(
            "OWL file not found at %s — skipping consistency check", owl_path
        )
        summary["consistency"] = {"consistent": None, "errors": ["OWL file not found"]}

    summary["status"] = "completed"
    logger.info(
        "=== Completed %s: %d commits, %d months, %d triples ===",
        repo_name, len(commits), len(monthly_metrics), len(triples),
    )
    return summary


# ── Batch Processing ─────────────────────────────────────────────────────────

def populate_batch(
    repos: list[str], config: PopulationConfig, output_dir: str
) -> list[dict]:
    """Run the population pipeline for a list of repositories.

    Paper 1 — batch mode for populating the SEO knowledge base across
    the full study sample (150 repositories).

    Args:
        repos: List of repository names (owner/name).
        config: Population configuration.
        output_dir: Directory to save per-repo summaries.

    Returns:
        List of summary dicts.
    """
    os.makedirs(output_dir, exist_ok=True)
    summaries: list[dict] = []

    for i, repo_name in enumerate(repos):
        logger.info("[%d/%d] Processing %s", i + 1, len(repos), repo_name)
        try:
            summary = populate_repo(repo_name, config)
        except Exception as exc:
            logger.error("Pipeline failed for %s: %s", repo_name, exc)
            summary = {
                "repo": repo_name,
                "status": "error",
                "error": str(exc),
            }

        summaries.append(summary)

        # Save individual summary
        safe_name = repo_name.replace("/", "__")
        summary_path = os.path.join(output_dir, f"{safe_name}_summary.json")
        with open(summary_path, "w") as f:
            json.dump(summary, f, indent=2, default=str)

    # Save combined summary
    combined_path = os.path.join(output_dir, "population_summary.json")
    with open(combined_path, "w") as f:
        json.dump(summaries, f, indent=2, default=str)

    # Log overall statistics
    completed = sum(1 for s in summaries if s.get("status") == "completed")
    total_triples = sum(s.get("total_triples", 0) for s in summaries)
    logger.info(
        "Batch complete: %d/%d repos, %d total triples",
        completed, len(repos), total_triples,
    )

    return summaries


# ── CLI ──────────────────────────────────────────────────────────────────────

def main() -> None:
    """CLI entry point for the ontology population pipeline.

    Paper 1 — supports single repo, batch file, and config file modes.
    """
    parser = argparse.ArgumentParser(
        description="SENSO Ontology Population Pipeline (Paper 1)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python populate.py --repo pallets/flask\n"
            "  python populate.py --repos-file repos.json --dataset seo\n"
            "  python populate.py --repo owner/name --config population.yaml\n"
        ),
    )
    parser.add_argument(
        "--repo", type=str,
        help="Single repository to populate (owner/name format)",
    )
    parser.add_argument(
        "--repos-file", type=str,
        help="JSON file containing list of repositories (strings or objects with 'full_name')",
    )
    parser.add_argument(
        "--fuseki-url", type=str, default="http://localhost:3030",
        help="Fuseki server URL (default: http://localhost:3030)",
    )
    parser.add_argument(
        "--dataset", type=str, default="seo",
        help="Fuseki dataset name (default: seo)",
    )
    parser.add_argument(
        "--config", type=str,
        help="Path to YAML configuration file",
    )
    parser.add_argument(
        "--output", type=str, default="data/processed/population/",
        help="Output directory for summaries (default: data/processed/population/)",
    )
    parser.add_argument(
        "--lookback-months", type=int, default=36,
        help="Number of months of history to mine (default: 36)",
    )
    parser.add_argument(
        "--batch-size", type=int, default=100,
        help="Triples per SPARQL INSERT batch (default: 100)",
    )
    parser.add_argument(
        "--skip-fuseki", action="store_true",
        help="Skip Fuseki loading (useful for JSON-LD generation only)",
    )
    parser.add_argument(
        "--env-file", type=str, default=".env",
        help="Path to .env file (default: .env)",
    )
    args = parser.parse_args()

    # Load environment
    load_dotenv(args.env_file)

    # Build config
    if args.config:
        config = PopulationConfig.from_yaml(args.config)
    else:
        config = PopulationConfig()

    # Override config with CLI args
    config.fuseki_url = args.fuseki_url
    config.dataset = args.dataset
    config.lookback_months = args.lookback_months
    config.batch_size = args.batch_size
    config.github_token = os.getenv("GITHUB_TOKEN", "")

    if args.skip_fuseki:
        # Replace the Fuseki URL with a sentinel to skip loading
        config.fuseki_url = ""

    # Resolve output directory relative to project root
    project_root = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    )
    output_dir = os.path.join(project_root, args.output)

    if args.repo:
        summary = populate_repo(args.repo, config)

        os.makedirs(output_dir, exist_ok=True)
        safe_name = args.repo.replace("/", "__")
        out_path = os.path.join(output_dir, f"{safe_name}_summary.json")
        with open(out_path, "w") as f:
            json.dump(summary, f, indent=2, default=str)

        logger.info("Summary saved to %s", out_path)

    elif args.repos_file:
        with open(args.repos_file) as f:
            repos_data = json.load(f)

        if isinstance(repos_data, list):
            if repos_data and isinstance(repos_data[0], dict):
                repos = [
                    r.get("full_name") or r.get("repo") or r.get("name")
                    for r in repos_data
                ]
            else:
                repos = repos_data
        else:
            logger.error("repos-file must contain a JSON array")
            sys.exit(1)

        repos = [r for r in repos if r]
        populate_batch(repos, config, output_dir)

    else:
        parser.error("Provide --repo or --repos-file")


if __name__ == "__main__":
    main()
